name: CI Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run -w packages/express-backend lint
      - run: npm run -w packages/react-frontend lint
      - run: npm run -w packages/react-frontend test || true
      - run: npm run -w packages/express-backend test || true
      - run: npm run -w packages/react-frontend build