name: Build and deploy Node.js app to Azure Web App - PropHunt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install --workspace packages/express-backend
        working-directory: packages/express-backend

      - name: Install dependencies for React frontend
        run: npm install --workspace packages/react-frontend
        working-directory: packages/react-frontend
      
      - name: Build React frontend
        run: npm run build
        working-directory: packages/react-frontend
      
        

      - name: Build and test
        run: |
          npm run build --if-present
          npm test --if-present
        working-directory: packages/express-backend

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*
        working-directory: packages/express-backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: packages/express-backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Unzip artifact for deployment
        run: unzip release.zip -d packages/express-backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id:
            ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "PropHunt"
          slot-name: ""
          package: ./packages/express-backend
          clean: true

      - name: "Set startup command"
        run:
          az webapp config set --resource-group
          "YourResourceGroupName" --name PropHunt --startup-file
          "npm start"
